### ISSUE TITLE
Error: zip method method 0 is not supported

### ISSUE THREAD

**Issue by johnothwolo** [pbatard/bled#3]
Hello, I'm a curious college mate trying to port this library to MacOS, but when I run the test programs I get errors such as:

`DECOMPRESS TO FILE:
Error: zip method 0 is not supported
  zip:	-14`
OR
`DECOMPRESS TO FILE:
Error: zip flags 1 and 8 are not supported
  zip:	-14`
The first one was for a zipped Github repo called flyver-sdk, and the second one was an ubuntu-16.04 LTS zipped image. I've only rewritten the libbb.h and defined Windows types and system calls.

**Comment by pbatard** [comment]
These look like limitations of busybox, which Bled will inherit.

For reference, method 0 (store) means no compression, in which case using zip is pretty pointless, so it's not surprising that busybox chose not to implement it.

If you want to use Bled or busybox, you will need to create zip archive that aren't using features that are unsupported.

**Comment by johnothwolo** [comment]
Well which means that the port worked, I thought I did something wrong.

**Comment by pbatard** [comment]
> I am actually trying to port Rufus as a whole

Wow! If you need help with that, let me know. Unfortunately, I think this will be a huge amount of work, given that Rufus is intricately tied to the Windows APIs when it comes to the UI and the formatting operations. And you'll probably have to drop Windows To Go support as well.

> and add MacOS support

Not so long ago, I had a look at [trying to support the creation of bootable USB from `InstalESD.dmg` on Windows](https://github.com/pbatard/rufus/issues/528#issuecomment-114309419), but found that, to do that, you'd need the ability to r/w HFS+ volumes, which of course is a major challenge on Windows, especially as there doesn't appear to exist any Open Source HFS+ driver with write capabilities...

Do you already know how you're planning to tackle the Win32 UI conversion to MacOS? There have been a few attempts at porting Rufus to Linux, all of which seemed to want to use Qt, but I can't say I've been impressed with Qt from the development's perspective, as they make it __incredibly difficult__ to link an application with a static Qt library (you have to build it yourself - wtf?!?) and even if you do, the application size is still expected to grow by an insane amount...

**Comment by johnothwolo** [comment]
I could try rewrite each header in objc, and find mac equivalents to the
windows apis, and if not, there must be some third party library. If all
else fails, I could use some code from winehq.
