### ISSUE TITLE
Compile as DLL

### ISSUE THREAD

**Issue by LFriede** [pbatard/bled#5]
Hi,

I started using bled in a Delphi project last weekend, to do this I compiled bled as DLL in Visual Studio 2019. I just changed the type in the project configuration. If you try this there will be two linker errors. The first one is easy to fix by adding `shlwapi.lib` so the `PathMatchSpec` function can be imported. I was unable to fix the second one: `LNK2019 Unresolved External Symbol _xz_crc32 in function _dec_block`.
I ended up commenting the lines where xz_crc32 is used because I don't need xz support, but I think it would be nice to be able compile bled as DLL out of the box. If you like I would PR my translated Delphi header or just link a gist so it can be found by others.

**Comment by pbatard** [comment]
Thanks for the report.

I'll try to have a look when I have a chance, but don't expect anything fast...

**Comment by pbatard** [comment]
I'm going to close this issue, because it's such a low priority for me that I don't think I'll ever be able to justify deallocating time from other matters to look into this. I'll accept a patch though.
