### ISSUE TITLE
Change IOBUF_SIZE to 64K in decompress_bunzip2.c

### ISSUE THREAD

**Issue by chazste** [pbatard/bled#6]
In testing the resolution to issue [#1422 in rufus,](https://github.com/pbatard/rufus/issues/1422) I/O performance is significantly worse when writing an image that in BZ compressed versus the straight uncompressed image. It seems that much of the performance loss is due to the [small] I/O buffer size. 

Please change IOBUF_SIZE to 64K in decompress_bunzip2.c

**Comment by chazste** [comment]
I've now tested this change on a second workstation (i.e. my "work" workstation, where I regularly do Yocto builds and this is my intended workflow) and am seeing results very similar to writing the uncompressed image.

I agree with your sentiment that if this change is implicated in a later regression it should be backed out. OTOH I don't expect any downside on any machine that is capable of running rufus/windows.

**Comment by pbatard** [comment]
I will apply this request. But you have to understand that this is __not__ a high priority. So please be patient, okay?
